[package]
name = "vulkan-example"
version = "0.1.0"
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "dylib"]

[dependencies]
bitflags = "*"
glam = "*"
